### PR TITLE
Add code suitable for both sets of changes.

### PR DESCRIPTION
**Pull request by chrisb2244**
This pull-request is simply to show a possible merge resolution for both the merge-AddNameToGreeting and merge-TimeOfDayGreeting branches into merge-main.

It's shown here as a merge of a different branch to allow those branches to remain unchanged for exercises.
Don't merge this! (but note the Action outcome).

### CODE REVIEW

**Comment by chrisb2244** [comment]
Reworked to include changes based on feedback from @jiegillet and @topherbuckley 
Should now have a more reasonable set of parent commits and fewer confusing merges in the process.
Some force pushes were used to achieve this :roll_eyes:

**Comment by topherbuckley** [comment]
I think this may be the first time I've tried to fetch a force pushed branch that had been tracked before the force push. When `git fetch` I no longer see any of your `merge-*` branches in my `git log`. I can only see the `cb-2020-update` and `master`. `git pull -f -a` also is not reviving them. `git branch` still shows my local copies, but when I check them out my HEAD disappears from the log. Never seen this behavior before. Other than a full repo rm and reclone any ideas how to bring my local repo back up to date?

**Comment by chrisb2244** [comment]
Try fetch. I'll check on my desktop pc now.

**Comment by topherbuckley** [comment]
No dice. I was using the wrong tag for pulling all commits `git pull -f -a` should be `git pull -f --all` btw.

**Comment by topherbuckley** [comment]
This is all I see now. 

image

**Comment by chrisb2244** [comment]
So my `fetch` gave (on branch merge-main)

```
$ git fetch
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 21 (delta 15), reused 15 (delta 9), pack-reused 0
Unpacking objects: 100% (21/21), done.
From github.com:oist/skillpill-git
   28ee00a..edd9c5c  merge-main              -> origin/merge-main
   c03967a..14db012  cb-2020-update          -> origin/cb-2020-update
   739232b..25ebda7  master                  -> origin/master
 + c918a5d...db34a79 merge-AddNameToGreeting -> origin/merge-AddNameToGreeting  (forced update)
 + 6cf67e5...c5e9f0c merge-TimeOfDayGreeting -> origin/merge-TimeOfDayGreeting  (forced update)
 + 46b11ac...46389c5 merge-conclude          -> origin/merge-conclude  (forced update)
```

and then 

```
$ git checkout merge-TimeOfDayGreeting
Switched to branch 'merge-TimeOfDayGreeting'
Your branch and 'origin/merge-TimeOfDayGreeting' have diverged,
and have 2 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

followed by `git reset --hard origin/merge-TimeOfDayGreeting` fixed this branch. Then I repeated for the other merge (and the conclude, I guess I'll do next).

**Comment by chrisb2244** [comment]
The reason your log doesn't have stuff showing is probably that it's at the bottom.
The `merge-main` branch was created as a separate branch from `master`, so it doesn't share a parent commit (`checkout --orphan`).
I was tempted to just use a separate repository for the merge exercise, but I got in trouble last time I created a separate tool/area for a mini-course exercise ;)

Try `git log --graph --oneline --decorate merge-main merge-AddNameToGreeting merge-TimeOfDayGreeting origin/merge-main` or similar (add the branches you care about rather than using `--all`, and it won't put them below the master branch and its related branches.

**Comment by chrisb2244** [comment]
And now we have a nice example of why not to do forced pushes when you have collaborators :D

**Comment by topherbuckley** [comment]
Aha! Indeed. That is a confusing history!

image

Is there a reason you chose to make it an orphan rather than how it was yesterday on top of master?

**Comment by chrisb2244** [comment]
It was an orphan already yesterday, but the ordering of branches in `log` is difficult to predict (or at least, I don't know how it works, and things I've read haven't made it clear to me).
Basically it tries to put them roughly in chronological order, I think, so perhaps my merge of changes to the PDF put the group associated with the lecture.tex files (master, cb-update-2020, etc) above the unrelated branches for the exercise (merge-*).

As to why have an orphan branch - I wanted them to be completely separate, since they have nothing to do with each other (and no shared code, the day1/day2 folders are not tracked in the merge-* branches which makes weird unexpected conflicts less likely).

This is the log I have (without the previous history cluttering it, shown in yours as the 'fork/...' bits, I think).
image

**Comment by topherbuckley** [comment]
Huh, alright. I'm curious to learn more about how the ordering works with the log in this case as mine makes it look like the 68f1ba3 "Initial commit" is a child of merge-conclude.

**Comment by topherbuckley** [comment]
Still not entirely sure how to plot the log with orphans in native git, but gitk seems to do a decent job:

https://gist.github.com/matthewmccullough/988077#gistcomment-2928496

**Pull request closed without merging**
